name: React Vite CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20.17.0  

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test -- --watchAll=false || true  

      - name: Build project
        run: npm run build

      - name: Build Docker image
        run: docker build -t job-genius-frontend:latest .

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.futurepoet }}
          password: ${{ secrets.zeze219246 }}

      - name: Push Docker image
        run: |
          docker tag job-genius-frontend:latest ${{ secrets.futurepoet }}/job-genius-frontend:latest
          docker push ${{ secrets.futurepoet }}/job-genius-frontend:latest
