name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.SUMMITLOVERS }}
        password: ${{ secrets.SUMMITLOVERS12345678 }}

    - name: Build Docker image
      run: docker build -t your-dockerhub-username/your-image-name:latest .

    - name: Push Docker image
      run: docker push your-dockerhub-username/your-image-name:latest
